#!/usr/bin/env bash

part_one_next_script_template=$(cat << 'EOF'
  #!/usr/bin/env bash 
  
  if [[ $PWD =~ /day-([0-9]+)/part-1$ ]]; then 
    day=${BASH_REMATCH[1]}
    ((day++))
  
    git switch -c day$day || git switch day$day
    gtaa && gtc "completed day $day, part 1"
    git push origin day$day

    cd ../part-2
    vi main.go
  else 
    echo "invalid working dir $PWD"
  fi
EOF
)

part_two_next_script_template=$(cat << 'EOF'
  #!/usr/bin/env bash 
  
  
  if [[ $PWD =~ /day-([0-9]+)/part-2$ ]]; then 
    day=${BASH_REMATCH[1]}
    ((day++))
  
    git switch -c day$day || git switch day$day
    gtaa && gtc "completed day $day, part 2"
    git push origin day$day

    cd ../..
    . scaffold "$day"
  else 
    echo "invalid working dir $PWD"
  fi
EOF
)

go_template=$(cat << 'EOF'
  package main
  
  import (
	  "fmt"
	  "log"
	  "os"
  )
  
  func main() {
	  inputData, err := os.ReadFile("input/example.txt")
	  if err != nil {
		  log.Fatal(err)
	  }
  
	  fmt.Println(string(inputData))
  }
EOF
)

if (( $# < 1 )); then 
  read -p "Day number: " day
else
  day="$1"
fi
mkdir -p "day-$day/part-1/input" "day-$day/part-2/input"

cd "day-$day/part-1"
echo "$go_template" > main.go 
echo "$part_one_next_script_template" > next
chmod 755 next
go mod init "github.com/trevorgrabham/AoC-26/day-$day/part-1"
touch input/example.txt input/challenge.txt

cd "../part-2"
echo "$go_template" > main.go 
echo "$part_two_next_script_template" > next
chmod 755 next
go mod init "github.com/trevorgrabham/AoC-26/day-$day/part-2"
touch input/example.txt input/challenge.txt

cd "../part-1"
vi input/example.txt && vi input/challenge.txt && vi main.go
