#!/usr/bin/env bash 


if [[ $PWD =~ /day-([0-9]+)/part-2$ ]]; then 
  day=${BASH_REMATCH[1]}
  ((day++))

  gtaa && gtc "completed day $day, part 2"
  git push origin
  cd ../..
  . scaffold "$day"
else 
  echo "invalid working dir $PWD"
fi
